"""
Bộ paraphrase test FULL — 50 case gốc + extended mới, 
đã loại trùng lặp code. Tổng: 179 case.

CẢNH BÁO: mã ICD-10 cần được đối chiếu qua icd.kcb.vn
trước khi dùng làm gold chính thức.
"""

# (paraphrase_text, expected_icd10_code, canonical_name_for_sanity)
PARAPHRASE_TEST_FULL = [
    ('loạn nhịp tim nhanh không đều ở tâm nhĩ', 'I48', 'Rung nhĩ'),
    ('nhồi máu cơ tim', 'I21.9', 'Nhồi máu cơ tim cấp'),
    ('tăng huyết áp', 'I10', 'Tăng huyết áp vô căn'),
    ('cao huyết áp', 'I10', 'Tăng huyết áp vô căn'),
    ('suy tim', 'I50.9', 'Suy tim không đặc hiệu'),
    ('suy tim ứ huyết', 'I50.0', 'Suy tim sung huyết'),
    ('bệnh mạch vành', 'I25.1', 'Bệnh tim do xơ vữa động mạch vành'),
    ('hở van hai lá', 'I34.0', 'Hở van hai lá'),
    ('hẹp van động mạch chủ', 'I35.0', 'Hẹp van động mạch chủ'),
    ('thiếu máu cơ tim cục bộ', 'I25.9', 'Bệnh tim thiếu máu cục bộ mạn tính, không đặc hiệu'),
    ('hen phế quản', 'J45.9', 'Hen phế quản'),
    ('hen suyễn', 'J45.9', 'Hen phế quản'),
    ('bệnh phổi tắc nghẽn mạn tính', 'J44.9', 'Bệnh phổi tắc nghẽn mạn tính, không đặc hiệu'),
    ('viêm phổi do vi khuẩn', 'J15.9', 'Viêm phổi do vi khuẩn không đặc hiệu'),
    ('viêm phổi thùy', 'J18.1', 'Viêm phổi thuỳ không đặc hiệu'),
    ('tràn dịch màng phổi', 'J90', 'Tràn dịch màng phổi'),
    ('suy hô hấp', 'J96.9', 'Suy hô hấp không đặc hiệu'),
    ('tiểu đường tuýp 2', 'E11.9', 'Đái tháo đường type 2 không có biến chứng'),
    ('đái tháo đường type 2', 'E11.9', 'Đái tháo đường type 2 không có biến chứng'),
    ('bệnh tiểu đường', 'E11.9', 'Đái tháo đường type 2 không có biến chứng'),
    ('suy giáp', 'E03.9', 'Suy giáp không đặc hiệu'),
    ('cường giáp', 'E05.9', 'Nhiễm độc giáp không đặc hiệu'),
    ('bướu cổ lành tính', 'E04.9', 'Bướu cổ không độc, không đặc hiệu'),
    ('trào ngược dạ dày thực quản', 'K21.9', 'Bệnh trào ngược dạ dày-thực quản'),
    ('trào ngược dạ dày', 'K21.9', 'Bệnh trào ngược dạ dày-thực quản'),
    ('viêm loét dạ dày', 'K25.9', 'Loét dạ dày, không đặc hiệu'),
    ('đau dạ dày', 'K30', 'Khó tiêu chức năng'),
    ('viêm tụy cấp', 'K85.9', 'Viêm tụy cấp, không đặc hiệu'),
    ('xơ gan do rượu', 'K70.3', 'Xơ gan do rượu'),
    ('viêm gan siêu vi B', 'B18.1', 'Viêm gan virus B mạn tính'),
    ('suy thận mạn', 'N18.9', 'Bệnh thận mạn, không đặc hiệu'),
    ('sỏi thận', 'N20.0', 'Sỏi thận'),
    ('nhiễm trùng tiểu', 'N39.0', 'Nhiễm khuẩn đường tiểu, chưa xác định vị trí'),
    ('viêm cầu thận cấp', 'N00.9', 'Hội chứng thận hư cấp tính, không đặc hiệu'),
    ('đột quỵ', 'I64', 'Đột quỵ không xác định xuất huyết hay nhồi máu'),
    ('tai biến mạch máu não', 'I64', 'Đột quỵ không xác định xuất huyết hay nhồi máu'),
    ('động kinh', 'G40.9', 'Động kinh, không đặc hiệu'),
    ('đau nửa đầu', 'G43.9', 'Đau nửa đầu, không đặc hiệu'),
    ('bệnh parkinson', 'G20', 'Bệnh Parkinson'),
    ('sa sút trí tuệ', 'F03', 'Sa sút trí tuệ, không đặc hiệu'),
    ('thoái hóa khớp gối', 'M17.9', 'Thoái hóa khớp gối, không đặc hiệu'),
    ('viêm khớp dạng thấp', 'M05.9', 'Viêm khớp dạng thấp huyết thanh dương tính, không đặc hiệu'),
    ('gout', 'M10.9', 'Gút, không đặc hiệu'),
    ('gút', 'M10.9', 'Gút, không đặc hiệu'),
    ('thiếu máu thiếu sắt', 'D50.9', 'Thiếu máu do thiếu sắt, không đặc hiệu'),
    ('ung thư phổi', 'C34.9', 'U ác phế quản hoặc phổi, không xác định vị trí'),
    ('u ác tính', 'C80.9', 'U ác tính, không xác định vị trí'),
    ('đa u tủy xương', 'C90.0', 'Đa u tuỷ'),
    ('sốt xuất huyết', 'A91', 'Sốt Dengue xuất huyết'),
    ('nhiễm trùng huyết', 'A41.9', 'Nhiễm khuẩn huyết, không đặc hiệu'),
    ('bệnh alzheimer', 'G30.9', 'bệnh alzheimer'),
    ('mất trí nhớ tuổi già', 'G30.9', 'bệnh alzheimer'),
    ('đau nửa đầu có aura', 'G43.1', 'migraine có aura'),
    ('đau đầu migraine kinh điển', 'G43.1', 'migraine có aura'),
    ('đau dây thần kinh tọa', 'M54.3', 'đau thần kinh tọa'),
    ('đau thần kinh liên sườn', 'G58.0', 'đau dây thần kinh liên sườn'),
    ('liệt mặt ngoại biên', 'G51.0', 'liệt bell'),
    ('liệt dây thần kinh số 7', 'G51.0', 'liệt bell'),
    ('hội chứng ống cổ tay', 'G56.0', 'hội chứng ống cổ tay'),
    ('tê tay kiểu ống cổ tay', 'G56.0', 'hội chứng ống cổ tay'),
    ('bệnh đa xơ cứng', 'G35', 'đa xơ cứng'),
    ('xơ cứng rải rác', 'G35', 'đa xơ cứng'),
    ('nhược cơ', 'G70.9', 'nhược cơ'),
    ('yếu cơ mắt sụp mí', 'G70.0', 'nhược cơ mắt'),
    ('cườm mắt', 'H25.9', 'đục thủy tinh thể tuổi già'),
    ('đục thủy tinh thể', 'H25.9', 'đục thủy tinh thể tuổi già'),
    ('tăng nhãn áp', 'H40.9', 'glôcôm'),
    ('cườm nước', 'H40.9', 'glôcôm'),
    ('glôcôm góc đóng', 'H40.2', 'glôcôm góc đóng'),
    ('viêm kết mạc', 'H10.9', 'viêm kết mạc'),
    ('đau mắt đỏ', 'H10.9', 'viêm kết mạc'),
    ('viêm màng bồ đào', 'H20.9', 'viêm màng bồ đào'),
    ('viêm giác mạc', 'H16.9', 'viêm giác mạc'),
    ('bong võng mạc', 'H33.0', 'bong võng mạc có rách'),
    ('viêm tai giữa', 'H66.9', 'viêm tai giữa'),
    ('viêm tai giữa cấp', 'H66.0', 'viêm tai giữa cấp'),
    ('viêm tai giữa mạn tính', 'H66.3', 'viêm tai giữa mạn tính'),
    ('viêm tai xương chũm', 'H70.9', 'viêm xương chũm'),
    ('ù tai', 'H93.1', 'ù tai'),
    ('chóng mặt do tai trong', 'H81.0', 'bệnh ménière'),
    ('bệnh ménière', 'H81.0', 'bệnh ménière'),
    ('đau thắt ngực', 'I20.9', 'đau thắt ngực'),
    ('suy tim trái', 'I50.1', 'suy tim trái'),
    ('rối loạn nhịp tim', 'I49.9', 'rối loạn nhịp tim không đặc hiệu'),
    ('bệnh cơ tim giãn', 'I42.0', 'bệnh cơ tim giãn'),
    ('viêm nội tâm mạc nhiễm khuẩn', 'I33.0', 'viêm nội tâm mạc nhiễm khuẩn'),
    ('viêm màng ngoài tim', 'I31.9', 'viêm màng ngoài tim'),
    ('giãn tĩnh mạch chân', 'I83.9', 'giãn tĩnh mạch chi dưới'),
    ('suy van tĩnh mạch', 'I87.2', 'suy van tĩnh mạch'),
    ('viêm tĩnh mạch huyết khối', 'I80.9', 'viêm tĩnh mạch và huyết khối tĩnh mạch'),
    ('huyết khối tĩnh mạch sâu', 'I80.2', 'huyết khối tĩnh mạch sâu chi dưới'),
    ('viêm mũi dị ứng', 'J30.4', 'viêm mũi dị ứng'),
    ('viêm mũi xoang', 'J32.9', 'viêm xoang mạn tính'),
    ('viêm họng cấp', 'J02.9', 'viêm họng cấp'),
    ('viêm amidan', 'J03.9', 'viêm amidan cấp'),
    ('viêm thanh quản', 'J04.0', 'viêm thanh quản cấp'),
    ('viêm phế quản cấp', 'J20.9', 'viêm phế quản cấp'),
    ('giãn phế quản', 'J47', 'giãn phế quản'),
    ('viêm phổi kẽ', 'J84.9', 'bệnh phổi kẽ'),
    ('xơ phổi', 'J84.1', 'bệnh phổi kẽ có xơ hóa'),
    ('khó nuốt', 'R13', 'khó nuốt'),
    ('nuốt nghẹn nuốt vướng', 'R13', 'khó nuốt'),
    ('ợ nóng ợ chua', 'K21.0', 'bệnh trào ngược dạ dày thực quản có viêm thực quản'),
    ('viêm dạ dày cấp', 'K29.1', 'viêm dạ dày cấp'),
    ('đau bao tử', 'K29.9', 'viêm dạ dày tá tràng'),
    ('sỏi đường mật', 'K80.5', 'sỏi đường mật'),
    ('sỏi ống mật chủ', 'K80.5', 'sỏi đường mật'),
    ('viêm túi thừa đại tràng', 'K57.3', 'viêm túi thừa đại tràng'),
    ('táo bón mạn tính', 'K59.0', 'táo bón mạn tính'),
    ('hội chứng ruột kích thích', 'K58.9', 'hội chứng ruột kích thích'),
    ('viêm ruột thừa cấp', 'K35.8', 'viêm ruột thừa cấp'),
    ('thoát vị bẹn', 'K40.9', 'thoát vị bẹn'),
    ('thoát vị rốn', 'K42.9', 'thoát vị rốn'),
    ('nứt hậu môn', 'K60.2', 'nứt hậu môn'),
    ('trĩ nội', 'K64.9', 'bệnh trĩ'),
    ('bệnh trĩ', 'K64.9', 'bệnh trĩ'),
    ('chàm thể tạng', 'L20.9', 'viêm da dị ứng'),
    ('viêm da dị ứng', 'L20.9', 'viêm da dị ứng'),
    ('viêm da mủ', 'L08.0', 'viêm da mủ'),
    ('phát ban do thuốc', 'L27.0', 'phát ban do thuốc'),
    ('mề đay dị ứng', 'L50.0', 'mề đay dị ứng'),
    ('mụn nhọt', 'L02.9', 'áp xe da nhọt nhọt đầu đinh'),
    ('áp xe da', 'L02.9', 'áp xe da nhọt nhọt đầu đinh'),
    ('đau lưng cấp', 'M54.5', 'đau thắt lưng'),
    ('đau lưng mạn', 'M54.5', 'đau thắt lưng'),
    ('đau lưng dưới', 'M54.5', 'đau thắt lưng'),
    ('thoái hóa đốt sống cổ', 'M47.9', 'thoái hóa cột sống'),
    ('thoái hóa đốt sống lưng', 'M47.9', 'thoái hóa cột sống'),
    ('viêm cột sống dính khớp', 'M45', 'viêm cột sống dính khớp'),
    ('viêm khớp thiếu niên', 'M08.0', 'viêm khớp thiếu niên'),
    ('loãng xương', 'M81.9', 'loãng xương'),
    ('xốp xương', 'M81.9', 'loãng xương'),
    ('gãy xương do loãng xương', 'M80.9', 'loãng xương có gãy xương bệnh lý'),
    ('sỏi niệu quản', 'N20.1', 'sỏi niệu quản'),
    ('sỏi bàng quang', 'N21.0', 'sỏi bàng quang'),
    ('viêm bể thận cấp', 'N10', 'viêm bể thận cấp'),
    ('viêm bàng quang', 'N30.9', 'viêm bàng quang'),
    ('tiểu không tự chủ', 'N39.4', 'tiểu không tự chủ'),
    ('són tiểu khi gắng sức', 'N39.3', 'tiểu không tự chủ do gắng sức'),
    ('phì đại tuyến tiền liệt', 'N40', 'phì đại tuyến tiền liệt'),
    ('u xơ tuyến tiền liệt', 'N40', 'phì đại tuyến tiền liệt'),
    ('tiền sản giật', 'O14.9', 'tiền sản giật'),
    ('nhiễm độc thai nghén', 'O14.9', 'tiền sản giật'),
    ('sản giật', 'O15.9', 'sản giật'),
    ('đái tháo đường thai kỳ', 'O24.4', 'đái tháo đường thai kỳ'),
    ('nhau tiền đạo', 'O44.0', 'nhau tiền đạo'),
    ('nhau bong non', 'O45.9', 'nhau bong non'),
    ('sảy thai tự nhiên', 'O03.9', 'sảy thai tự nhiên'),
    ('thai ngoài tử cung', 'O00.9', 'thai ngoài tử cung'),
    ('viêm vùng chậu nữ', 'N73.9', 'viêm vùng chậu nữ'),
    ('vàng da sơ sinh', 'P59.9', 'vàng da sơ sinh'),
    ('vàng da bệnh lý sơ sinh', 'P55.9', 'bệnh tan máu sơ sinh'),
    ('suy hô hấp sơ sinh', 'P22.0', 'hội chứng suy hô hấp sơ sinh'),
    ('nhiễm trùng sơ sinh', 'P36.9', 'nhiễm trùng sơ sinh'),
    ('tim bẩm sinh', 'Q24.9', 'dị tật bẩm sinh tim'),
    ('hở hàm ếch', 'Q35.9', 'khe hở vòm miệng'),
    ('sứt môi hở hàm ếch', 'Q37.9', 'khe hở vòm miệng kèm khe hở môi'),
    ('trật khớp háng bẩm sinh', 'Q65.0', 'trật khớp háng bẩm sinh một bên'),
    ('sốt không rõ nguyên nhân', 'R50.9', 'sốt không rõ nguyên nhân'),
    ('đau ngực không do tim', 'R07.4', 'đau ngực không đặc hiệu'),
    ('đau bụng cấp', 'R10.0', 'bụng cấp'),
    ('xuất huyết tiêu hóa trên', 'K92.2', 'xuất huyết tiêu hóa'),
    ('xuất huyết tiêu hóa dưới', 'K92.2', 'xuất huyết tiêu hóa'),
    ('ung thư gan nguyên phát', 'C22.9', 'u ác gan'),
    ('ung thư dạ dày', 'C16.9', 'u ác dạ dày'),
    ('ung thư đại trực tràng', 'C19', 'u ác đại tràng'),
    ('ung thư vú', 'C50.9', 'u ác vú'),
    ('ung thư tuyến tiền liệt', 'C61', 'u ác tuyến tiền liệt'),
    ('ung thư cổ tử cung', 'C53.9', 'u ác cổ tử cung'),
    ('bạch cầu cấp', 'C95.0', 'bệnh bạch cầu cấp'),
    ('ung thư máu', 'C95.9', 'bệnh bạch cầu'),
    ('tâm thần phân liệt thể Paranoid', 'F20.0', 'tâm thần phân liệt thể paranoid'),
    ('rối loạn lo âu lan tỏa', 'F41.1', 'rối loạn lo âu lan tỏa'),
    ('ám ảnh sợ khoảng trống', 'F40.0', 'rối loạn ám ảnh sợ khoảng trống'),
    ('rối loạn ám ảnh cưỡng chế', 'F42.9', 'rối loạn ám ảnh cưỡng chế'),
    ('trầm cảm nặng', 'F32.9', 'giai đoạn trầm cảm'),
    ('rối loạn hoảng sợ', 'F41.0', 'rối loạn hoảng sợ'),
    ('nghiện rượu mạn', 'F10.2', 'rối loạn tâm thần và hành vi do rượu hội chứng lệ thuộc'),
    ('rối loạn giấc ngủ', 'G47.9', 'rối loạn giấc ngủ'),
]

# Total: 179 cases
